# Generated by Django 5.0.4 on 2025-06-25 06:50

import django.db.models.deletion
import docwallet.models
import labour_license.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicetasks', '0001_initial'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessIdentityStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Labour License', editable=False, max_length=20)),
                ('classification_of_establishment', models.CharField(max_length=255)),
                ('category_of_establishment', models.CharField(max_length=255)),
                ('legal_name_of_business', models.CharField(max_length=255)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('business_pan', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_identity_structure_pan)),
                ('date_of_commencement', models.DateField()),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_businesses', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_businesses', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_identity_structure', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_business_identity', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLocationProofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Labour License', editable=False, max_length=20)),
                ('principal_place_of_business', models.JSONField(default=dict)),
                ('nature_of_possession', models.CharField(max_length=255)),
                ('address_proof', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_location_address_proof)),
                ('rental_agreement', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_location_rental_agreement)),
                ('bank_statement', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_location_bank_statement)),
                ('additional_space', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=3)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_businesses_location_proofs', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_businesses_location_proofs', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_location_proofs', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_business_locations_proof', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSpaceBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField(default=dict)),
                ('nature_of_possession', models.CharField(max_length=255)),
                ('address_proof', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.additional_business_space_address_proof)),
                ('rental_agreement', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.additional_business_space_rental_agreement)),
                ('business_location_proofs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_space_business', to='labour_license.businesslocationproofs')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRegistrationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Labour License', editable=False, max_length=20)),
                ('certificate_of_incorporation', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_registration_documents_certificate_of_incorporation)),
                ('memorandum_of_articles', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_registration_documents_memorandum_of_articles)),
                ('local_language_name_board_photo_business', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_registration_documents_local_language_name_board_photo_business)),
                ('authorization_letter', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.business_registration_documents_authorization_letter)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_businesses_registration_docs', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_businesses_registration_docs', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_registration_documents', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_business_registration', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFilingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Labour License', editable=False, max_length=20)),
                ('review_certificate', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.review_filing_certificate)),
                ('draft_filing_certificate', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.draft_filing_certificate)),
                ('review_certificate_status', models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default=None, max_length=20, null=True)),
                ('filing_status', models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('filed', 'Filed'), ('sent for approval', 'Sent for Approval'), ('resubmitted', 'Resubmitted')], default=None, max_length=20, null=True)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('resubmission', 'Resubmission'), ('sent for approval', 'Sent for Approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default=None, max_length=20, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_businesses_review_filing_certificate', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_businesses_review_filing_certificate', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_filing_certificate', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_review_filing_certificate', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='SignatoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Labour License', editable=False, max_length=20)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_signatory', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signatory', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_signatory_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_signatory_details', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='signatoryDetailsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhar_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.signatory_details_aadhar_image)),
                ('pan_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.signatory_details_pan_image)),
                ('photo_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=labour_license.helpers.signatory_details_photo_image)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=3)),
                ('address', models.TextField(blank=True, null=True)),
                ('signatory_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatory_details_info', to='labour_license.signatorydetails')),
            ],
        ),
    ]
