# Generated by Django 5.0.4 on 2025-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocationproofs',
            name='additional_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signatorydetailsinfo',
            name='residential_address',
            field=models.BooleanField(default=False),
        ),
    ]
