# Generated by Django 5.0.4 on 2025-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotersignatoryinfo',
            name='residential_same_as_aadhaar_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='any_existing_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='applying_for_casual_taxable_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='is_this_voluntary_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrationinfo',
            name='opting_for_composition_scheme',
            field=models.BooleanField(default=False),
        ),
    ]
