# Generated by Django 5.0.4 on 2025-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_test0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalplacedetails',
            name='nature_of_possession_of_premise',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('rented', 'Rented'), ('leased', 'Leased')], max_length=255, null=True),
        ),
    ]
