version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tara_dev_backend
  - source: nginx/http.conf
    destination: /tmp

hooks:
  BeforeInstall:
    - location: scripts/bootstrap-ec2.sh
      timeout: 600
      runas: root
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
    - location: scripts/pull_images.sh
      timeout: 600
      runas: ubuntu

  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/migrate_and_static.sh
      timeout: 600
      runas: ubuntu

  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 180
      runas: ubuntu
