version: 0.2

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.docker/**/*'

env:
  parameter-store:
    DOCKER_HUB_USERNAME: /tara_backend/docker-credentials/username
    DOCKER_HUB_PASSWORD: /tara_backend/docker-credentials/password
    DOCKER_IMAGE_NAME: /tara_backend/docker/image_name

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "[Install] Installing Docker..."
      - apt-get update && apt-get install -y docker.io jq awscli

  pre_build:
    commands:
      - echo "[PreBuild] Logging in to Docker Hub..."
      - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      # Determine slot and port
      - CURRENT_SLOT=$(aws ssm get-parameter --name "/tara_backend/current_slot" --query "Parameter.Value" --output text || echo "blue")
      - if [ "$CURRENT_SLOT" = "blue" ]; then
          NEXT_SLOT="green";
          NEXT_PORT="8002";
          echo "Switching from BLUE to GREEN deployment";
        else
          NEXT_SLOT="blue";
          NEXT_PORT="8001";
          echo "Switching from GREEN to BLUE deployment";
        fi

      # Construct full tag with slot
      - export IMAGE_TAG="$COMMIT_HASH-$NEXT_SLOT"
      - export DOCKER_IMAGE=$DOCKER_IMAGE_NAME
      - echo "DOCKER_IMAGE=$DOCKER_IMAGE"
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "[Build] Building Docker image..."
      - docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
      - echo "[Build] Pushing to Docker Hub..."
      - docker push $DOCKER_IMAGE:$IMAGE_TAG

  post_build:
    commands:
      - echo "[PostBuild] Updating SSM and writing env file..."
      - aws ssm put-parameter --name "/tara_backend/current_slot" --value "$NEXT_SLOT" --type "String" --overwrite
      - echo "DOCKER_IMAGE=$DOCKER_IMAGE" > image_vars.env
      - echo "IMAGE_TAG=$IMAGE_TAG" >> image_vars.env
      - echo "DEPLOY_SLOT=$NEXT_SLOT" >> image_vars.env
      - echo "BACKEND_PORT=$NEXT_PORT" >> image_vars.env
      - echo "PREVIOUS_SLOT=$CURRENT_SLOT" >> image_vars.env
      - chmod 644 image_vars.env

artifacts:
  files:
    - image_vars.env
    - appspec.yml
    - scripts/*
    - nginx/*
    - docker-compose.yml
