# Generated by Django 5.0.4 on 2025-06-25 06:51

import django.db.models.deletion
import docwallet.models
import msme_registration.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicetasks', '0001_initial'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClassificationInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='MSME Registration', editable=False, max_length=20)),
                ('major_activity', models.CharField(blank=True, choices=[('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service')], default='MANUFACTURING', max_length=20)),
                ('nature_of_business', models.CharField(blank=True, max_length=100)),
                ('nic_codes', models.JSONField(blank=True, default=dict, null=True)),
                ('number_of_persons_employed', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business_classification', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_classification', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_classification_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_business_classification_details', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='MSME Registration', editable=False, max_length=20)),
                ('organisation_type', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('pan_of_business_or_COI', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.upload_pan_path)),
                ('aadhar_of_signatory', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.upload_aadhar_path)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=255)),
                ('Are_you_previously_registered_UAM', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A'), ('not_applicable', 'Not Applicable'), ('not_available', 'Not Available')], default='no', max_length=20)),
                ('UAM_number', models.CharField(blank=True, max_length=50, null=True)),
                ('has_business_commenced', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A'), ('not_applicable', 'Not Applicable'), ('not_available', 'Not Available')], default='no', max_length=20)),
                ('date_of_commencement', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msme_bi_assignee', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msme_bi_reviewer', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msme_business_identity_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_msme_business_identity', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='MsmeReviewFilingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='MSME Registration', editable=False, max_length=20)),
                ('review_certificate', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.review_filing_certificate_path)),
                ('review_certificate_status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default=None, max_length=20)),
                ('draft_income_file', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.draft_filing_certificate)),
                ('filing_status', models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('filed', 'Filed'), ('sent for approval', 'Sent for Approval'), ('resubmitted', 'Resubmitted')], default=None, max_length=20, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('resubmission', 'Resubmission'), ('sent for approval', 'Sent for Approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default=None, max_length=20, null=True)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msme_reviewfc_assignee', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msme_reviewfc_reviewer', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msme_review_certificates', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msme_review_tasks', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='MSME Registration', editable=False, max_length=20)),
                ('official_address_of_enterprise', models.JSONField(blank=True, null=True)),
                ('bank_statement_or_cancelled_cheque', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.upload_bank_statement_or_cancelled_cheque_path)),
                ('official_address_of_proof', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.upload_official_address_proof_path)),
                ('location_of_plant', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], default='no', max_length=3)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_registered_address', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registered_address', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_address_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_registered_address_details', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='LocationOfPlantOrUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_details', models.JSONField(blank=True, null=True)),
                ('registered_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_of_plant_or_unit', to='msme_registration.registeredaddress')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoverAndInvestmentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='MSME Registration', editable=False, max_length=20)),
                ('turnover_in_inr', models.JSONField(blank=True, default=dict, null=True)),
                ('investment_in_plant_and_machinery', models.IntegerField(blank=True, null=True)),
                ('have_you_filed_itr_previous_year', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A'), ('not_applicable', 'Not Applicable'), ('not_available', 'Not Available')], max_length=20)),
                ('are_you_registered_under_gst', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('exempted', 'Exempted'), ('upload', 'Upload GST Certificate')], max_length=10, null=True)),
                ('gst_certificate', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=msme_registration.helpers.upload_gst_certificate_path)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_turnover_investment_declaration', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_turnover_investment_declaration', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_turnover_details', to='servicetasks.servicetask')),
            ],
        ),
    ]
