# Generated by Django 5.0.4 on 2025-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msmereviewfilingcertificate',
            name='review_certificate_status',
            field=models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default=None, max_length=20, null=True),
        ),
    ]
