# Generated by Django 5.0.4 on 2025-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msme_registration', '0002_alter_msmereviewfilingcertificate_review_certificate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclassificationinputs',
            name='major_activity',
            field=models.CharField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Service', 'Service')], default='Manufacturing', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='Are_you_previously_registered_UAM',
            field=models.BooleanField(blank=True, default=False, help_text='Check if previously registered under UAM', null=True),
        ),
        migrations.AlterField(
            model_name='businessidentity',
            name='has_business_commenced',
            field=models.BooleanField(blank=True, default=False, help_text='Check if business has commenced', null=True),
        ),
        migrations.AlterField(
            model_name='registeredaddress',
            name='location_of_plant',
            field=models.BooleanField(blank=True, default=False, help_text='Check if you have a location of plant or unit', null=True),
        ),
        migrations.AlterField(
            model_name='turnoverandinvestmentdeclaration',
            name='are_you_registered_under_gst',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('exempted', 'Exempted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turnoverandinvestmentdeclaration',
            name='have_you_filed_itr_previous_year',
            field=models.BooleanField(blank=True, default=False, help_text='Check if you have filed ITR for the previous year', null=True),
        ),
    ]
