# Generated by Django 5.0.4 on 2025-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_tax_returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofessionalincomeinfo',
            name='book_maintained',
            field=models.BooleanField(default=False, help_text='Is the user maintaining books of accounts?'),
        ),
        migrations.AlterField(
            model_name='businessprofessionalincomeinfo',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Is the user GST registered?'),
        ),
        migrations.AlterField(
            model_name='businessprofessionalincomeinfo',
            name='opting_for_presumptive_taxation',
            field=models.BooleanField(default=False, help_text='Is the user opting for presumptive taxation?'),
        ),
        migrations.AlterField(
            model_name='capitalgainsequitymutualfund',
            name='sell_any_foreign_sales',
            field=models.BooleanField(default=False, help_text='Has the user made any foreign sales?'),
        ),
        migrations.AlterField(
            model_name='capitalgainsequitymutualfund',
            name='sell_any_unlisted_sales',
            field=models.BooleanField(default=False, help_text='Has the user made any unlisted sales?'),
        ),
        migrations.AlterField(
            model_name='capitalgainsproperty',
            name='reinvestment_made',
            field=models.BooleanField(default=False, help_text='Has the user made any reinvestment?'),
        ),
        migrations.AlterField(
            model_name='foreignincomeinfo',
            name='tax_paid_abroad',
            field=models.BooleanField(default=False, help_text='Has the user paid tax abroad?'),
        ),
        migrations.AlterField(
            model_name='giftincomedocument',
            name='was_it_marriage_related',
            field=models.BooleanField(default=False, help_text='Was the gift received during marriage?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='agriculture_income',
            field=models.BooleanField(default=False, help_text='Is the user earning agriculture income?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='business_income',
            field=models.BooleanField(default=False, help_text='Is the user earning business or professional income?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='capital_gains',
            field=models.BooleanField(default=False, help_text='Is the user earning capital gains income?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='house_property_income',
            field=models.BooleanField(default=False, help_text='Is the user earning income from house property?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='other_income',
            field=models.BooleanField(default=False, help_text='Is the user earning any other income?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='salary_income',
            field=models.BooleanField(default=False, help_text='Is the user earning salary income?'),
        ),
    ]
