# Generated by Django 5.0.4 on 2025-07-07 11:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docwallet', '0002_auto_20250707_1711'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='document_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
