# Generated by Django 5.0.4 on 2025-06-25 06:51

import django.db.models.deletion
import docwallet.models
import trade_license.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicetasks', '0001_initial'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('partner', 'Partner'), ('director', 'Director'), ('owner', 'Owner'), ('other', 'Other')], max_length=50)),
                ('aadhaar_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.signatory_details_aadhar_image)),
                ('pan_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.signatory_details_pan_image)),
                ('passport_photo', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.signatory_details_passport)),
                ('residential_address', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=3)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applicant', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applicant', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_task', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorporation_certificate', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_registration_documents_certificate_of_incorporation)),
                ('photo_of_premises', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_registration_documents_photo_of_premises)),
                ('property_tax_receipt', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_registration_documents_property_tax_receipt)),
                ('rental_agreement', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_registration_documents_rental_agreement)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business_registration_docs', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_registration_docs', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_documents', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_registration_task', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_business', models.CharField(max_length=50)),
                ('legal_name_of_business', models.CharField(max_length=255)),
                ('business_pan', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_identity_structure_pan)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=50)),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_identity', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_identity_task', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_premises', models.CharField(max_length=100)),
                ('trade_description', models.TextField()),
                ('address', models.JSONField(default=dict)),
                ('nature_of_possession', models.CharField(max_length=100)),
                ('trade_area', models.CharField(max_length=100)),
                ('road_type', models.CharField(max_length=100)),
                ('address_proof', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_location_address_proof)),
                ('rental_agreement', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_location_rental_agreement)),
                ('bank_statement', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.business_location_bank_statement)),
                ('additional_space', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], default='no', max_length=3)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_businesses_location', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_businesses_location', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_locations', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_location_task', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSpaceBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.JSONField(default=dict)),
                ('nature_of_possession', models.CharField(max_length=100)),
                ('address_proof', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.additional_business_space_address_proof)),
                ('rental_agreement', models.FileField(storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.additional_business_space_rental_agreement)),
                ('business_locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_address_details', to='trade_license.businesslocation')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFilingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=20)),
                ('review_certificate', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.review_filing_certificate)),
                ('draft_filing_certificate', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.draft_filing_certificate)),
                ('review_certificate_status', models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default=None, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], max_length=20, null=True)),
                ('filing_status', models.CharField(blank=True, choices=[('in progress', 'In Progress'), ('filed', 'Filed'), ('sent for approval', 'Sent for Approval'), ('resubmitted', 'Resubmitted')], default=None, max_length=20, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('resubmission', 'Resubmission'), ('sent for approval', 'Sent for Approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default=None, max_length=20, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business_review_filing_certificate', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_review_filing_certificate', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_certificate', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_certificate_task', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='SignatoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=100)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_signatory_detail', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signatory_detail', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_or_directors_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signatory_task', to='servicetasks.servicetask')),
            ],
        ),
        migrations.CreateModel(
            name='SignatoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhar_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.promoter_or_directors_aadhaar)),
                ('pan_image', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.promoter_or_directors_pan)),
                ('passport_photo', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.promoter_or_directors_passport_photo)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('residential_address', models.CharField(choices=[('yes', 'YES'), ('no', 'No')], max_length=3)),
                ('address', models.TextField(blank=True, null=True)),
                ('signatory_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatory_info', to='trade_license.signatorydetails')),
            ],
        ),
        migrations.CreateModel(
            name='TradeLicenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_new_license', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10)),
                ('trade_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_license_file', models.FileField(blank=True, null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=trade_license.helpers.trade_license_document)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('sent for approval', 'Sent for Approval'), ('revoked', 'Revoked')], default='in progress', max_length=20)),
                ('service_type', models.CharField(default='Trade License', editable=False, max_length=100)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tradelicense', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tradelicense', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_license_details', to='usermanagement.servicerequest')),
                ('service_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_license_task', to='servicetasks.servicetask')),
            ],
        ),
    ]
