# Generated by Django 5.0.4 on 2025-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='residential_address',
            field=models.BooleanField(default=False, help_text='Is the residential address same as Aadhaar address?'),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='additional_space',
            field=models.BooleanField(default=False, help_text='Is there an additional space for business?'),
        ),
        migrations.AlterField(
            model_name='signatoryinfo',
            name='residential_address',
            field=models.BooleanField(default=False, help_text='Is the residential address same as Aadhaar address?'),
        ),
        migrations.AlterField(
            model_name='tradelicensedetails',
            name='apply_new_license',
            field=models.BooleanField(default=True, help_text='Is this a new trade license application?'),
        ),
    ]
