# Generated by Django 5.0.4 on 2025-06-25 06:49

import django.db.models.deletion
import invoicing.helpers
import invoicing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.BigIntegerField(validators=[invoicing.models.validate_account_number])),
                ('ifsc_code', models.CharField(max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=invoicing.helpers.signatures_upload_path)),
                ('gst_registered', models.BooleanField()),
                ('gstin', models.CharField(blank=True, max_length=120, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_common_format', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10)),
                ('gstin', models.CharField(max_length=20, null=True)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('series_code', models.CharField(blank=True, max_length=10, null=True)),
                ('running_number_start', models.IntegerField(default=1)),
                ('include_branch_code', models.BooleanField(default=False)),
                ('include_financial_year', models.BooleanField(default=True)),
                ('include_series_code', models.BooleanField(default=False)),
                ('include_running_number', models.BooleanField(default=True)),
                ('reset_every_fy', models.BooleanField(default=True)),
                ('maintain_sequence_per_branch', models.BooleanField(default=False)),
                ('maintain_sequence_per_gstin', models.BooleanField(default=False)),
                ('format_version', models.PositiveIntegerField(default=1)),
                ('invoicing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_formats', to='invoicing.invoicingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('terms', models.CharField(max_length=500)),
                ('financial_year', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('format_version', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('month', models.IntegerField()),
                ('sales_person', models.CharField(blank=True, max_length=60, null=True)),
                ('order_number', models.CharField(blank=True, max_length=60, null=True)),
                ('place_of_supply', models.CharField(max_length=500)),
                ('billing_address', models.JSONField(blank=True, default=dict, null=True)),
                ('shipping_address', models.JSONField(blank=True, default=dict, null=True)),
                ('item_details', models.JSONField(blank=True, default=list)),
                ('gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_code', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('subtotal_amount', models.FloatField(null=True)),
                ('shipping_amount', models.FloatField(null=True)),
                ('total_cgst_amount', models.FloatField(null=True)),
                ('total_sgst_amount', models.FloatField(null=True)),
                ('total_igst_amount', models.FloatField(null=True)),
                ('pending_amount', models.FloatField(null=True)),
                ('amount_invoiced', models.FloatField(null=True)),
                ('payment_status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('terms_and_conditions', models.CharField(blank=True, max_length=500, null=True)),
                ('applied_tax', models.BooleanField(default=False)),
                ('shipping_tax', models.FloatField(null=True)),
                ('shipping_amount_with_tax', models.FloatField(null=True)),
                ('selected_gst_rate', models.FloatField(null=True)),
                ('invoice_status', models.CharField(max_length=60)),
                ('customer_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_pan', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('invoicing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoicing.invoicingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('gst_registered', models.CharField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_type', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('opening_balance', models.IntegerField(null=True)),
                ('entity_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('has_multiple_branches', models.BooleanField(blank=True, default=False, null=True)),
                ('branches', models.JSONField(blank=True, default=list, help_text='List of branches with their details if has_multiple_branches is True', null=True)),
                ('invoicing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='invoicing.invoicingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('written off', 'written off')], default='cash', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_number', models.IntegerField()),
                ('tax_deducted', models.CharField(choices=[('no_tax', 'No Tax deducted'), ('tds_income_tax', 'Yes, TDS (Income Tax)')], default='no_tax', max_length=60)),
                ('amount_withheld', models.FloatField(null=True)),
                ('comments', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice_receipts', to='invoicing.invoice')),
            ],
            options={
                'unique_together': {('invoice', 'payment_number')},
            },
        ),
        migrations.CreateModel(
            name='GoodsAndServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_value', models.FloatField(null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=500, null=True)),
                ('gst_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_preference', models.CharField(blank=True, max_length=60, null=True)),
                ('selling_price', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('invoicing_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_and_services', to='invoicing.invoicingprofile')),
            ],
            options={
                'unique_together': {('invoicing_profile', 'name')},
            },
        ),
    ]
