# Generated by Django 5.0.4 on 2025-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gst_registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceformat',
            name='is_common_format',
            field=models.BooleanField(default=True, help_text='Indicates if this format applies to all GSTINs under the invoicing profile'),
        ),
    ]
