# Generated by Django 5.0.4 on 2025-06-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_incorporation', '0001_initial'),
        ('servicetasks', '0001_initial'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedpaidupsharecapital',
            name='service_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_authorized_capital', to='servicetasks.servicetask'),
        ),
        migrations.AddField(
            model_name='directors',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_directors_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directors',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_directors_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directors',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directors_details', to='usermanagement.servicerequest'),
        ),
        migrations.AddField(
            model_name='directors',
            name='service_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_directors_details', to='servicetasks.servicetask'),
        ),
        migrations.AddField(
            model_name='directorsdetails',
            name='directors_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='company_incorporation.directors'),
        ),
        migrations.AddField(
            model_name='proposedcompanydetails',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proposed_company_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposedcompanydetails',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposed_company_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposedcompanydetails',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_company_details', to='usermanagement.servicerequest'),
        ),
        migrations.AddField(
            model_name='proposedcompanydetails',
            name='service_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_proposed_company_details', to='servicetasks.servicetask'),
        ),
        migrations.AddField(
            model_name='registeredofficeaddressdetails',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_registered_office_address_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredofficeaddressdetails',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registered_office_address_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registeredofficeaddressdetails',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_office_address', to='usermanagement.servicerequest'),
        ),
        migrations.AddField(
            model_name='registeredofficeaddressdetails',
            name='service_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_registered_office_address', to='servicetasks.servicetask'),
        ),
        migrations.AddField(
            model_name='reviewfilingcertificate',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incorporation_review_filing_certificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfilingcertificate',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incorporation_review_filing_certificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewfilingcertificate',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_request_review_certificate', to='usermanagement.servicerequest'),
        ),
        migrations.AddField(
            model_name='reviewfilingcertificate',
            name='service_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_task_review_certificate', to='servicetasks.servicetask'),
        ),
        migrations.AddField(
            model_name='shareholders',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shareholders_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareholders',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shareholders_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareholders',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders_details', to='usermanagement.servicerequest'),
        ),
        migrations.AddField(
            model_name='shareholders',
            name='service_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_task_shareholders_details', to='servicetasks.servicetask'),
        ),
        migrations.AddField(
            model_name='shareholdersdetails',
            name='shareholders_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='company_incorporation.shareholders'),
        ),
    ]
