# Generated by Django 5.0.4 on 2025-06-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_incorporation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedpaidupsharecapital',
            name='service_type',
            field=models.CharField(default='Company Incorporation', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='directors',
            name='service_type',
            field=models.CharField(default='Company Incorporation', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='directorsdetails',
            name='details_of_existing_directorships',
            field=models.BooleanField(blank=True, default=False, help_text='Does the director have any existing directorships?', null=True),
        ),
        migrations.AlterField(
            model_name='directorsdetails',
            name='din_number',
            field=models.BooleanField(blank=True, default=False, help_text='Does the director have a Director Identification Number (DIN)?', null=True),
        ),
        migrations.AlterField(
            model_name='directorsdetails',
            name='dsc',
            field=models.BooleanField(default=False, help_text='Does the director have a Digital Signature Certificate (DSC)?'),
        ),
        migrations.AlterField(
            model_name='directorsdetails',
            name='is_this_director_also_shareholder',
            field=models.BooleanField(blank=True, default=False, help_text='Is this director also a shareholder?', null=True),
        ),
        migrations.AlterField(
            model_name='directorsdetails',
            name='residential_same_as_aadhaar_address',
            field=models.BooleanField(blank=True, default=False, help_text='Is the residential address same as Aadhaar address?', null=True),
        ),
        migrations.AlterField(
            model_name='proposedcompanydetails',
            name='service_type',
            field=models.CharField(default='Company Incorporation', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredofficeaddressdetails',
            name='service_type',
            field=models.CharField(default='Company Incorporation', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewfilingcertificate',
            name='service_type',
            field=models.CharField(default='Company Incorporation', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='shareholders',
            name='service_type',
            field=models.CharField(default='Company Incorporation', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='shareholdersdetails',
            name='residential_same_as_aadhaar_address',
            field=models.BooleanField(blank=True, default=False, help_text='Is the residential address same as Aadhaar address?', null=True),
        ),
    ]
