# Generated by Django 5.0.4 on 2025-07-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='children_education_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='conveyance_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='overtime_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='transport_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='travelling_allowance',
            field=models.IntegerField(default=0),
        ),
    ]
