# Generated by Django 5.0.4 on 2025-07-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employeesalaryhistory_basic_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('financial_year', models.CharField(max_length=10)),
                ('new_joinees', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20)),
                ('exits', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20)),
                ('attendance', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20)),
                ('bonuses', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20)),
                ('salary_revision', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20)),
                ('tds', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20)),
                ('finalize', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_workflow', to='payroll.payrollorg')),
            ],
        ),
    ]
