# Generated by Django 5.0.4 on 2025-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworkflow',
            name='loans_and_advances',
            field=models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20),
        ),
    ]
