# Generated by Django 5.0.4 on 2025-07-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_employeesalarydetails_is_variable_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_type', models.CharField(choices=[('manual', 'Manual'), ('geo', 'Geo Location'), ('face', 'Face Recognition'), ('qr', 'QR Code'), ('timesheet', 'Timesheet'), ('biometric', 'Biometric Device'), ('auto', 'System Auto')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('device_info', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employeemanagement')),
            ],
        ),
    ]
