# Generated by Django 5.0.4 on 2025-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employeecredentials_alter_attendancelog_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='deduction_type',
            new_name='deduction_name',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='payslip_name',
        ),
        migrations.AddField(
            model_name='deduction',
            name='calculation_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deduction',
            name='component_type',
            field=models.CharField(default='Fixed', max_length=60),
        ),
        migrations.AddField(
            model_name='deduction',
            name='includes_epf_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='includes_esi_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
