# Generated by Django 5.0.4 on 2025-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_rename_deduction_type_deduction_deduction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='bonus_incentive',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)')], default='O+', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20, null=True),
        ),
    ]
