# Generated by Django 5.0.4 on 2025-07-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_employeesalaryhistory_bonus_incentive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)')], default='O+', max_length=15, null=True),
        ),
    ]
