# Generated by Django 5.0.4 on 2025-07-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_employeepersonaldetails_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='other_deductions_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="List of {'component_name': 'Name', 'amount': 500}"),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='other_earnings_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries with 'component_name' and 'amount'"),
        ),
    ]
