# Generated by Django 5.0.4 on 2025-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_employeesalaryhistory_other_deductions_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='monthly_fixed_tds',
            field=models.FloatField(null=True),
        ),
    ]
