# Generated by Django 5.0.4 on 2025-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_employeesalaryhistory_monthly_fixed_tds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epf',
            name='admin_charge_in_ctc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='allow_employee_level_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='apply_components_if_wage_below_15k',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='employee_contribution_rate',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='employer_contribution_rate',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='epf_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='include_employer_contribution_in_ctc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='prorate_restricted_pf_wage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='esi',
            name='employee_contribution',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='esi',
            name='employer_contribution',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='esi',
            name='esi_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
