# Generated by Django 5.0.4 on 2025-07-29 08:58

import django.db.models.deletion
import payroll.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_alter_epf_admin_charge_in_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworkflow',
            name='adhoc_bonuses',
            field=models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20),
        ),
        migrations.AddField(
            model_name='payrollworkflow',
            name='lock_payroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pt',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='holidaymanagement',
            name='applicable_for',
        ),
        migrations.CreateModel(
            name='AttendanceGeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_location', to='payroll.worklocations')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_locations', to='payroll.payrollorg')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFaceRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('front', 'Front Face'), ('left', 'Left Profile'), ('right', 'Right Profile'), ('upper_angle', 'Upper Angle'), ('lower_angle', 'Lower Angle'), ('back', 'back')], max_length=50)),
                ('image_file', models.FileField(upload_to=payroll.helpers.employee_image_upload_path)),
                ('labels', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='payroll.employeecredentials')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('EL', 'Earned Leave'), ('LOP', 'Loss of Pay')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('attach_file', models.FileField(blank=True, null=True, upload_to=payroll.helpers.leave_attachments)),
                ('cc_to', models.ManyToManyField(blank=True, related_name='cc_leaves', to='payroll.employeecredentials')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='payroll.employeecredentials')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='payroll.employeecredentials')),
            ],
        ),
        migrations.AddField(
            model_name='holidaymanagement',
            name='applicable_for',
            field=models.ManyToManyField(blank=True, related_name='applicable_holidays', to='payroll.worklocations'),
        ),
    ]
