# Generated by Django 5.0.4 on 2025-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_alter_epf_admin_charge_in_ctc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pt',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
