# Generated by Django 5.0.4 on 2025-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_pt_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworkflow',
            name='lock_payroll',
            field=models.BooleanField(default=False),
        ),
    ]
