# Generated by Django 5.0.4 on 2025-07-29 09:12

import django.db.models.deletion
import payroll.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_payrollworkflow_adhoc_bonuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=120)),
                ('year_of_passing', models.IntegerField()),
                ('upload_certificate', models.FileField(blank=True, null=True, upload_to=payroll.helpers.employee_education_certificate)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='payroll.employeecredentials')),
            ],
        ),
    ]
