# Generated by Django 5.0.4 on 2025-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_payrollworkflow_lock_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworkflow',
            name='adhoc_bonuses',
            field=models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('approved', 'approved')], default='in progress', max_length=20),
        ),
    ]
