# Generated by Django 5.0.4 on 2025-07-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_employeeeducationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_leave_applications', to='payroll.leavemanagement'),
        ),
    ]
