# Generated by Django 5.0.4 on 2025-07-24 07:27

import django.db.models.deletion
import payroll.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_payrollworkflow_adhoc_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceGeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('radius', models.IntegerField(blank=True, null=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_location', to='payroll.worklocations')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_locations', to='payroll.payrollorg')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFaceRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('front', 'Front Face'), ('left', 'Left Profile'), ('right', 'Right Profile'), ('upper_angle', 'Upper Angle'), ('lower_angle', 'Lower Angle'), ('back', 'back')], max_length=50)),
                ('image_file', models.FileField(upload_to=payroll.helpers.employee_image_upload_path)),
                ('labels', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='payroll.employeecredentials')),
            ],
        ),
    ]
