# Generated by Django 5.0.4 on 2025-08-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemanagement',
            name='employee_level',
            field=models.CharField(blank=True, choices=[('0', '0 - CEO / Director / Executive'), ('1', '1 - Vice President / General Manager'), ('2', '2 - HR Manager / Department Manager'), ('3', '3 - Team Lead / Project Lead'), ('4', '4 - Senior Employee / Supervisor'), ('5', '5 - Employee / Trainee / Intern')], default='5', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeReportingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewing_team', to='payroll.employeemanagement')),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='payroll.employeemanagement')),
                ('reporting_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='payroll.employeemanagement')),
            ],
        ),
    ]
