# Generated by Django 5.0.4 on 2025-08-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_employeemanagement_employee_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemanagement',
            name='employee_level',
            field=models.CharField(blank=True, choices=[('0', '0 - CEO / Director / Executive'), ('1', '1 - Vice President / General Manager'), ('2', '2 - HR Manager'), ('3', '3 - Department Manager'), ('4', '4 - Team Lead / Project Lead'), ('5', '5 - Employee / Trainee / Intern')], default='5', max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='LeaveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.leaveapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employeecredentials')),
            ],
        ),
    ]
