# Generated by Django 5.0.4 on 2025-07-28 12:00

import django.db.models.deletion
import payroll.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_attendancegeotag_employeefacerecognition'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('EL', 'Earned Leave'), ('LOP', 'Loss of Pay')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('attach_file', models.FileField(blank=True, null=True, upload_to=payroll.helpers.leave_attachments)),
                ('cc_to', models.ManyToManyField(blank=True, related_name='cc_leaves', to='payroll.employeecredentials')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='payroll.employeecredentials')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='payroll.employeecredentials')),
            ],
        ),
    ]
