# Generated by Django 5.0.4 on 2025-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaymanagement',
            name='applicable_for',
        ),
        migrations.AddField(
            model_name='holidaymanagement',
            name='applicable_for',
            field=models.ManyToManyField(blank=True, related_name='applicable_holidays', to='payroll.worklocations'),
        ),
    ]
