# Generated by Django 5.0.4 on 2025-06-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_msme_registered',
            field=models.BooleanField(default=False, help_text='Is the business MSME registered?'),
        ),
        migrations.AlterField(
            model_name='gstdetails',
            name='is_composition_scheme',
            field=models.BooleanField(default=False, help_text='Is the business registered under composition scheme?'),
        ),
        migrations.AlterField(
            model_name='gstdetails',
            name='is_export_sez',
            field=models.BooleanField(default=False, help_text='Is the business registered for export under SEZ?'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if the module is active'),
        ),
        migrations.AlterField(
            model_name='modulesubscription',
            name='via_suite',
            field=models.BooleanField(default=False, help_text='Indicates if this subscription is part of a suite'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if the service is active'),
        ),
        migrations.AlterField(
            model_name='servicepaymentinfo',
            name='captured',
            field=models.BooleanField(default=False, help_text='Indicates if the payment has been captured'),
        ),
        migrations.AlterField(
            model_name='servicepaymentinfo',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the plan is active'),
        ),
        migrations.AlterField(
            model_name='userfeaturepermission',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the permission is currently active'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates if the user account is active'),
        ),
    ]
