# Generated by Django 5.0.4 on 2025-06-25 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_business_is_msme_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkyc',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 12-digit Aadhaar number', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F)', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
