# Generated by Django 5.0.4 on 2025-06-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_alter_userkyc_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextsuitesubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Indicates if the subscription will auto-renew'),
        ),
        migrations.AlterField(
            model_name='modulesubscription',
            name='auto_renew',
            field=models.BooleanField(default=False, help_text='Indicates if the subscription will auto-renew'),
        ),
        migrations.AlterField(
            model_name='subscriptioncycle',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Indicates if this cycle has been paid'),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_completed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed the registration process'),
        ),
    ]
