# Generated by Django 5.0.4 on 2025-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_contextsuitesubscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymanagerialpersonnel',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
