# Generated by Django 5.0.4 on 2025-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_keymanagerialpersonnel_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleusagecycle',
            name='actual_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moduleusagecycle',
            name='usage_count',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
