# Generated by Django 5.0.4 on 2025-07-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_moduleusagecycle_actual_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='usermanagement.business'),
        ),
    ]
