# Generated by Django 5.0.4 on 2025-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_alter_context_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='trade_name',
            new_name='legal_name',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_nature',
            field=models.CharField(blank=True, choices=[('Agency or Sales House', 'Agency or Sales House'), ('Agriculture', 'Agriculture'), ('Art and Design', 'Art and Design'), ('Automotive', 'Automotive'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Consumer Packaged Goods', 'Consumer Packaged Goods'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Financial Services', 'Financial Services'), ('Food Services (Restaurants/Fast Food)', 'Food Services (Restaurants/Fast Food)'), ('Gaming', 'Gaming'), ('Government', 'Government'), ('Health Care', 'Health Care'), ('Interior Design', 'Interior Design'), ('Internal', 'Internal'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Mining and Logistics', 'Mining and Logistics'), ('Non-Profit', 'Non-Profit'), ('Publishing and Web Media', 'Publishing and Web Media'), ('Real Estate', 'Real Estate'), ('Retail (E-Commerce and Offline)', 'Retail (E-Commerce and Offline)'), ('Services', 'Services'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Travel/Hospitality', 'Travel/Hospitality'), ('Web Designing', 'Web Designing'), ('Web Development', 'Web Development'), ('Writers', 'Writers'), ('Software Services', 'Software Services')], default=None, max_length=50, null=True),
        ),
    ]
