# Generated by Django 5.0.4 on 2025-07-09 10:30

import django.db.models.deletion
import document_drafting.helpers
import docwallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0007_alter_context_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Name of the category', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the category', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata related to the category', null=True)),
                ('created_at', models.DateField(auto_now_add=True, help_text='Timestamp when the category was created')),
                ('updated_at', models.DateField(auto_now=True, help_text='Timestamp when the category was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Custom title for this event instance', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Custom description for this event instance', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('yet_to_start', 'Yet to be Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='yet_to_start', help_text='Current status of the event instance.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(help_text='Name of the document', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the document', null=True)),
                ('template', models.TextField(blank=True, help_text='Template for the document', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata related to the document', null=True)),
                ('created_at', models.DateField(auto_now_add=True, help_text='Timestamp when the document was created')),
                ('updated_at', models.DateField(auto_now=True, help_text='Timestamp when the document was last updated')),
                ('category', models.ForeignKey(blank=True, help_text='Category associated with the document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_drafting.category')),
            ],
        ),
        migrations.CreateModel(
            name='ContextWiseEventAndDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yet_to_start', 'Yet to be Started'), ('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='yet_to_start', help_text='Current status of this document', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category associated with this document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='document_drafting.category')),
                ('document', models.ForeignKey(help_text='Document template being used', on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='document_drafting.document')),
                ('event_instance', models.ForeignKey(help_text='Event instance this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_drafting.eventinstance')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDraftDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_data', models.JSONField(blank=True, default=dict, help_text='JSON field to store draft data', null=True)),
                ('file', models.FileField(blank=True, help_text='File associated with the draft (optional)', null=True, storage=docwallet.models.PrivateS3Storage(), upload_to=document_drafting.helpers.draft_document_file)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.OneToOneField(help_text='Event document this draft belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='draft_details', to='document_drafting.contextwiseeventanddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Name of the field', max_length=255)),
                ('label', models.CharField(help_text='Label for the field', max_length=255)),
                ('field_type', models.CharField(help_text='Type of the field (e.g., text, number, date)', max_length=50)),
                ('is_required', models.BooleanField(default=False, help_text='Indicates if the field is required')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Timestamp when the field was created')),
                ('updated_at', models.DateField(auto_now=True, help_text='Timestamp when the field was last updated')),
                ('document', models.ForeignKey(help_text='Document associated with the field', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='document_drafting.document')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the event', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the event', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata related to the event', null=True)),
                ('created_at', models.DateField(auto_now_add=True, help_text='Timestamp when the event was created')),
                ('updated_at', models.DateField(auto_now=True, help_text='Timestamp when the event was last updated')),
                ('category', models.ForeignKey(blank=True, help_text='Category associated with the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='document_drafting.category')),
            ],
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='event',
            field=models.ForeignKey(help_text='The base event template', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='document_drafting.events'),
        ),
        migrations.AddField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event associated with the document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_drafting.events'),
        ),
        migrations.CreateModel(
            name='UserDocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.OneToOneField(help_text='Context for the document draft (e.g., personal, business)', on_delete=django.db.models.deletion.CASCADE, related_name='document_draft', to='usermanagement.context')),
            ],
        ),
        migrations.AddField(
            model_name='contextwiseeventanddocument',
            name='context',
            field=models.ForeignKey(help_text='Context for this event instance', on_delete=django.db.models.deletion.CASCADE, related_name='context_event_documents', to='document_drafting.userdocumentdraft'),
        ),
        migrations.CreateModel(
            name='UserFavouriteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Timestamp when the document was favourited')),
                ('document', models.OneToOneField(help_text='Document that is favourited', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='document_drafting.document')),
                ('draft', models.ForeignKey(blank=True, help_text='Draft associated with the favourite document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite_documents', to='document_drafting.userdocumentdraft')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contextwiseeventanddocument',
            unique_together={('event_instance', 'document')},
        ),
    ]
