# Generated by Django 5.0.4 on 2025-07-09 11:19

import document_drafting.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_drafting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinstance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventinstance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='eventinstance',
            name='title',
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.FileField(blank=True, help_text='Template for the document', null=True, upload_to=document_drafting.helpers.document_template_path),
        ),
    ]
