# Generated by Django 5.0.4 on 2025-07-09 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_drafting', '0002_remove_eventinstance_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contextwiseeventanddocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contextwiseeventanddocument',
            name='created_by',
            field=models.OneToOneField(blank=True, help_text='User who created this event document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextwiseeventanddocument',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document template being used', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='document_drafting.document'),
        ),
        migrations.AlterField(
            model_name='contextwiseeventanddocument',
            name='event_instance',
            field=models.ForeignKey(blank=True, help_text='Event instance this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='document_drafting.eventinstance'),
        ),
    ]
