# Generated by Django 5.0.4 on 2025-07-09 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_drafting', '0003_alter_contextwiseeventanddocument_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdraftdetail',
            name='status',
            field=models.CharField(choices=[('yet_to_start', 'Yet to be Started'), ('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', help_text='Current status of this draft', max_length=50),
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='progress',
            field=models.FloatField(default=0.0, help_text='Progress percentage of this event instance'),
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='status',
            field=models.CharField(choices=[('yet_to_start', 'Yet to be Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='yet_to_start', help_text='Current status of this event instance', max_length=50),
        ),
        migrations.AlterField(
            model_name='contextwiseeventanddocument',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category associated with this document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_documents', to='document_drafting.category'),
        ),
        migrations.AlterField(
            model_name='contextwiseeventanddocument',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contextwiseeventanddocument',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Document template being used', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_context', to='document_drafting.document'),
        ),
        migrations.AlterField(
            model_name='contextwiseeventanddocument',
            name='event_instance',
            field=models.ForeignKey(blank=True, help_text='Event instance this document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_instance_documents', to='document_drafting.eventinstance'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category associated with the document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_category', to='document_drafting.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Event associated with the document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_event', to='document_drafting.events'),
        ),
    ]
