# Generated by Django 5.0.4 on 2025-07-11 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_drafting', '0004_documentdraftdetail_status_eventinstance_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouritedocument',
            name='document',
            field=models.ForeignKey(help_text='Document that is favourited', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='document_drafting.document'),
        ),
    ]
