# Generated by Django 5.0.4 on 2025-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_drafting', '0005_alter_userfavouritedocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfields',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata related to the field', null=True),
        ),
    ]
