# Generated by Django 5.0.4 on 2025-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_drafting', '0006_documentfields_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextwiseeventanddocument',
            name='file_name',
            field=models.CharField(blank=True, help_text='Name of the file associated with this document', max_length=255, null=True),
        ),
    ]
